# Azure DevOps
# CI pipeline for PSRule.Rules

variables:
  version: '0.1.0'
  buildConfiguration: 'Release'

# Use build number format, i.e. 0.1.0-B1811001
name: $(version)-B$(date:yyMM)$(rev:rrr)

trigger: none
  # branches:
  #   include:
  #   - 'master'
  # tags:
  #   include:
  #   - 'v0.*'

pr: none
  # branches:
  #   include:
  #   - 'master'

stages:

# Build pipeline
- stage: Build
  displayName: Build
  jobs:
  - job:
    strategy:
      matrix:
        Linux:
          displayName: 'Linux'
          imageName: 'ubuntu-16.04'
    pool:
      vmImage: $(imageName)
    displayName: 'Docker'
    steps:
    # Install pipeline dependencies
    - powershell: ./.azure-pipelines/pipeline-deps.ps1
      displayName: 'Install dependencies'

    # Build module
    - task: Docker@2
      displayName: Login to registry
      inputs:
        command: login
        containerRegistry: AzureDevOps-PSRule.Rules

    # Build module
    - powershell: Invoke-Build BuildImageLinux -Configuration $(buildConfiguration) -Build $(Build.BuildNumber)
      displayName: 'Build container image'

    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        containerRegistry: AzureDevOps-PSRule.Rules
        tags:
          docker.pkg.github.com/BernieWhite/TestRepo/ps-rule:latest-alpine
